#!/bin/bash

sudo apt update  ; sudo apt clean ; sudo apt autoclean ; sudo apt upgrade -y ; sudo apt autoremove -y 
sudo apt install toilet lolcat    figlet tar neofetch git vim ripgrep curl  python3 python3-pip3  wget  nmap xsltproc  htop   p7zip-full  masscan  gdu  hydra  build-essential libpcap-dev libusb-1.0-0-dev libnetfilter-queue-dev   jq    gnupg lsb-release -y 

#go-install
echo -e "\033[34m[+]Installing GO.. For $OS \033[m"
sudo add-apt-repository ppa:longsleep/golang-backports -y
sudo apt update
sudo apt install golang -y 


#wordlist
mkdir -p   ~/wordlist  ~/wordlist/dns
chmod +rwx ~/wordlist

git clone https://github.com/orwagodfather/WordList   ~/wordlist/gofather-wordlist
wget https://raw.githubusercontent.com/six2dez/OneListForAll/main/onelistforallshort.txt  -P ~/wordlist/

wget https://raw.githubusercontent.com/emadshanab/admin-paths/main/admin.txt -P ~/wordlist/

wget https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt -P ~/wordlist/dns/

wget https://wordlists-cdn.assetnote.io/data/automated/httparchive_subdomains_2024_05_28.txt -P  ~/wordlist/dns/

rm ~/wordlist/resolvers.txt ; curl -L https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt -o ~/wordlist/resolvers.txt


mkdir -p ~/tools
cd ~/tools

echo -e "\033[33m[+]Installing...Tools \033[m";

curl -LO https://github.com/findomain/findomain/releases/latest/download/findomain-linux.zip
unzip findomain*
sudo chmod +x findomain
sudo mv findomain /usr/bin/findomain
sudo rm findomain*

echo -e "\033[36m[+]nmap-vulners Updating...\033[m" 
chmod +rwx /usr/share/nmap/scripts/
sudo rm  vulners.nse* 
sudo rm  /usr/share/nmap/scripts/vulners.nse*
sudo rm http-vulners-regex.nse
sudo rm  /usr/share/nmap/scripts/http-vulners-regex.nse
sudo wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse ;sudo mv vulners.nse /usr/share/nmap/scripts/ 
echo 'root' | sudo  -kS nmap --script-updatedb


sudo pip3 install setuptools
#xss-tools
git clone https://github.com/devanshbatham/paramspider
cd paramspider
chmod +x *
sudo pip3 install .
cd ..


#gf
wget https://raw.githubusercontent.com/emadshanab/Gf-Patterns-Collection/main/set-all.sh
chmod +x *
bash set-all.sh
rm set-all.sh

git  clone https://github.com/takshal/freq
cd freq
chmod +x *
sudo go build main.go
sudo mv main /usr/local/bin/freq
cd ..

sudo pip3 install fuzzywuzzy
sudo pip3 install requests
sudo pip3 install tld

git clone https://github.com/s0md3v/XSStrike.git
cd XSStrike
chmod +x *
cd ..

#subdomains
git clone https://github.com/aboul3la/Sublist3r.git
cd Sublist3r
chmod +x *
sudo pip3 install  -r requirements.txt
sudo python3 setup.py install
cd ..

#sqli
git clone https://github.com/r0oth3x49/ghauri.git
cd ghauri
sudo pip3 install  -r requirements.txt
chmod +x *
sudo python3 setup.py install
cd ..

#subdomaintakover
wget https://github.com/Stratus-Security/Subdominator/releases/latest/download/Subdominator
sudo chmod +x Subdominator
sudo mv Subdominator /usr/local/bin/subdominator


#secret

git clone https://github.com/m4ll0k/SecretFinder.git secretfinder
cd secretfinder
chmod +x *
sudo pip3 install -r requirements.txt
cd ..

git clone https://github.com/blechschmidt/massdns.git ~/tools/massdns 
cd ~/tools/massdns
sudo make
sudo make install 
cd ..

#cors
git clone  https://github.com/s0md3v/Corsy.git
cd Corsy
chmod +x *
sudo pip3 install -r requirements.txt
sudo pip3 install requests
cd ..


#lfi
git clone http://github.com/mzfr/liffy
cd liffy
chmod +x *
sudo pip3 install -r requirements.txt
cd ..


#open-redirect
git clone https://github.com/devanshbatham/openredirex
cd openredirex
chmod +x *
sudo bash setup.sh
sudo pip3 install tqdm
cd ..

sudo pip3 install uro
sudo pip3 install sqlmap
sudo  pip3 install git+https://github.com/xnl-h4ck3r/waymore.git -v
sudo  pip3 install git+https://github.com/xnl-h4ck3r/xnLinkFinder.git -v
sudo  pip3 install git+https://github.com/sanjai-AK47/ShodanX
sudo pip3 install appdirs
sudo pip3 install alive_progress


#go-tools

wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
unzip subfinder_2.6.6_linux_amd64.zip
sudo mv subfinder /usr/local/bin/
rm subfinder_2.6.6_linux_amd64.zip


wget https://github.com/projectdiscovery/shuffledns/releases/download/v1.1.0/shuffledns_1.1.0_linux_amd64.zip
unzip shuffledns_1.1.0_linux_amd64.zip
sudo mv shuffledns /usr/local/bin/
rm *.zip
rm README.md LICENSE.md

wget https://github.com/d3mondev/puredns/releases/download/v2.1.1/puredns-Linux-amd64.tgz
tar -xvf  puredns-Linux-amd64.tgz
sudo mv puredns /usr/local/bin/
rm *.tgz

wget https://github.com/projectdiscovery/httpx/releases/download/v1.6.5/httpx_1.6.5_linux_amd64.zip
unzip httpx_1.6.5_linux_amd64.zip
sudo mv httpx /usr/local/bin/
rm *.zip
rm README.md LICENSE.md

wget https://github.com/projectdiscovery/katana/releases/download/v1.1.0/katana_1.1.0_linux_amd64.zip
unzip katana_1.1.0_linux_amd64.zip
sudo mv katana /usr/local/bin/
rm *.zip
rm README.md LICENSE.md

wget https://github.com/lc/gau/releases/download/v2.2.3/gau_2.2.3_linux_amd64.tar.gz
tar -xvf  gau_2.2.3_linux_amd64.tar.gz
sudo mv gau /usr/local/bin/
rm *gz
rm README.md LICENSE*


wget https://github.com/projectdiscovery/naabu/releases/download/v2.3.1/naabu_2.3.1_linux_amd64.zip
unzip naabu_2.3.1_linux_amd64.zip
sudo mv naabu /usr/local/bin/
rm *.zip
rm README.md LICENSE.md


wget https://github.com/projectdiscovery/nuclei/releases/download/v3.2.9/nuclei_3.2.9_linux_amd64.zip
unzip *.zip
sudo mv nuclei /usr/local/bin/
rm *.zip
rm README.md LICENSE.md

wget https://github.com/KathanP19/Gxss/releases/download/v4.1/Gxss_4.1_Linux_x86_64.tar.gz
tar -xvf Gxss_4.1_Linux_x86_64.tar.gz
sudo mv Gxss /usr/local/bin/gxss
rm *gz
rm README* LICENSE*

echo -e "\033[36m[+]Installing... Go-Tools  \033[m";
go install github.com/i5nipe/nipejs@latest
go install -v github.com/LukaSikic/subzy@latest
go install -v github.com/tomnomnom/gf@latest
go install -v github.com/tomnomnom/anew@latest
go install -v github.com/tomnomnom/qsreplace@latest
go install github.com/tomnomnom/unfurl@latest
go install github.com/ffuf/ffuf/v2@latest
#copy-path-to-bin
sudo cp -r ~/go/bin/*  /usr/local/bin/ 
sudo cp -r ~/gopath/bin/*  /usr/local/bin/ 

echo -e ${GREEN}"[+]Done! Go Tools installed."; echo "";
sleep 1.5

curl -LO https://raw.githubusercontent.com/lc/gau/master/.gau.toml
mv .gau.toml ~/.gau.toml




cd ~
echo -e "\033[33m[+]Installing nuclei templates \033[m"
git clone https://github.com/projectdiscovery/nuclei-templates.git ~/nuclei-templates
git clone https://github.com/0xKayala/fuzzing-templates.git ~/fuzzing-templates

cd ~

