#!/bin/bash

# Ensure the script is invoked with at least one argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <target_list_file>"
    exit 1
fi

TARGET_LIST=$1

# Create necessary directories and set permissions
mkdir -p shodan
chmod +rwx shodan/

# Notify start of the process
echo "shodanx uncover started ips -->" | notify -silent -bulk

# Iterate over each target in the list
cat "$TARGET_LIST" | while read host; do
    # Run shodanx commands for various queries and append results to shodan/ip.txt
    shodanx domain -to 20 -ra -d "$host" -o shodan/ip.txt
    shodanx custom -to 20 -ra -cq "ssl:$host" -o shodan/ip.txt
    shodanx custom -to 20 -ra -cq "hostname:$host" -o shodan/ip.txt
    shodanx custom -to 20 -ra -cq "ssl.cert.subject.cn:$host" -o shodan/ip.txt
    shodanx custom -to 20 -ra -cq "http.title:'$host'" -o shodan/ip.txt
    echo "$host" | cut -d'.' -f1 | anew org
done

# Iterate over each organization in the org file and perform shodanx queries
cat org | while read host; do
    shodanx custom -to 20 -ra -cq "org:$host" -o shodan/ip.txt
    rm org
    uncover -q '"ssl:$domain"' -silent -e shodan,zoomeye,netlas | anew shodan/ip.txt
    uncover -q '"hostname:$domain"' -silent -e shodan,zoomeye,netlas | anew shodan/ip.txt
    uncover -q '"http.title:$domain"' -silent -e shodan,zoomeye,netlas | anew shodan/ip.txt
done

# Perform favicon-hash operation using FavFreak and shodanx
cat "$TARGET_LIST" | while read host; do
    echo "$host" | httpx | python3 ~/tools/FavFreak/favfreak.py --shodan -o fav
    ls fav/* | tr -d fav/ | tr -d .txt | anew hash.txt
done

cat hash.txt | while read host; do
    shodanx custom -to 20 -ra -cq "http.favicon.hash:'$host'" -o shodan/ip.txt
    rm hash.txt
    rm -rf fav/
done

# Filter IPs from shodan/ip.txt based on host list
cat "$TARGET_LIST" | while read host; do
    cat shodan/ip.txt | sort -u|tlsx -san -cn -silent |grep  -F $host | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | anew shodan/ips.txt
done

# Additional IP filtering using hakip2host
cat "$TARGET_LIST" | while read host; do
    cat shodan/ip.txt |sort -u| hakip2host |grep  -F $host | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | anew shodan/ips.txt
done

# Clean up temporary files
rm shodan/ip.txt
