#!/bin/bash

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Define the base directory and DNS wordlist
BASE_DIR="/home/kali/recon"
dnswordlist="~/wordlist/dns/httparchive_subdomains_2024_05_28.txt"

echo -e "${GREEN}subenum started${NC}" | notify -silent -bulk

# Iterate through each subdirectory in the base directory
for dir in "$BASE_DIR"/*/; do
    # Check if the directory contains a roots.txt file
    if [[ -f "$dir/roots.txt" ]]; then
        echo -e "${GREEN}passive subenum started: $dir${NC}" | notify -silent -bulk
        echo -e "${BLUE}Processing $dir/roots.txt${NC}"

        # Read each domain from roots.txt and execute the specified commands
        while read -r domain; do
            echo -e "${YELLOW}passive subenum started: $domain${NC}" | notify -silent -bulk
            echo "$domain" | anew "$dir/tmp.txt"
            python3 ~/tools/Sublist3r/sublist3r.py -d "$domain" -o "$dir/tmp.txt"
            findomain -t "$domain" -q | anew "$dir/tmp.txt"
            subfinder -all -d "$domain" | anew "$dir/tmp.txt"
            shodanx subdomain -d "$domain" -to 50 -ra -o "$dir/tmp.txt"
        done < "$dir/roots.txt"

        # Download and update resolver.txt
        echo -e "${BLUE}Updating resolver.txt${NC}" | notify -silent -bulk
        rm ~/wordlist/resolvers.txt
        curl -L https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt -o ~/wordlist/resolvers.txt

        # Run puredns bruteforce
        echo -e "${BLUE}Running puredns bruteforce${NC}" | notify -silent -bulk
        puredns bruteforce "$dnswordlist" -r ~/wordlist/resolvers.txt -d "$dir/roots.txt" -w "$dir/tmp.txt"

        # Filter out-of-scope domains and notify
        echo -e "${BLUE}Filtering out-of-scope domains${NC}" | notify -silent -bulk
        cat "$dir/tmp.txt" | inscope -s "$dir/outscope.txt" -r | anew "$dir/allsubdomains.txt" | notify -silent -bulk

        # Resolve domains
        echo -e "${BLUE}Resolving domains${NC}" | notify -silent -bulk
        puredns resolve "$dir/allsubdomains.txt" -r ~/wordlist/resolvers.txt | anew "$dir/all-resolve-subdomains.txt"

        echo -e "${BLUE}Port scanning started${NC}" | notify -silent -bulk
        cat "$dir/all-resolve-subdomains.txt" | sort -u | naabu -top-ports 1000 -silent | anew "$dir/naabu.txt"

        echo -e "${BLUE}httpx started${NC}" | notify -silent -bulk
        cat "$dir/naabu.txt" | httpx -silent | anew "$dir/httpx.txt"

        echo -e "${BLUE}httpx tech started${NC}" | notify -silent -bulk
        cat "$dir/httpx.txt" | httpx -title -td -sc -server -silent | anew "$dir/httpx-tech.txt"

        echo -e "${BLUE}httpx asn enum started${NC}" | notify -silent -bulk
        cat "$dir/httpx.txt" | httpx -asn -silent | anew "$dir/httpx-asn.txt"

        echo -e "${BLUE}Running nuclei tech templates${NC}" | notify -silent -bulk
        rm -rf ~/nuclei-templates
        git clone https://github.com/projectdiscovery/nuclei-templates.git ~/nuclei-templates
        cat "$dir/httpx.txt" | nuclei -t ~/nuclei-templates/ -tags tech -o "$dir/nuclei-tech.txt" | notify -silent -bulk

        echo -e "${GREEN}subetakeover checking started: $domain${NC}" | notify -silent -bulk
        echo -e "${BLUE}Checking for subdomain takeovers${NC}"

        mkdir -p "$dir/takeover"

        curl -L https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/8b2bc8ab8ef801d4342bb4ec4fedb5460296da29/subdomain-takeover/detect-all-takeovers.yaml -o ~/nuclei-templates/http/takeovers/detect-all-takeovers.yaml
        cat "$dir/all-resolve-subdomains.txt" | httpx | nuclei -t ~/nuclei-templates/http/takeovers/ -o "$dir/takeover/takeovers-nuclei.txt" | notify -silent -bulk

        echo -e "${GREEN}subetakeover checking finished: $domain${NC}" | notify -silent -bulk

    else
        echo -e "${RED}roots.txt not found in $dir${NC}" | notify -silent -bulk
    fi
done

echo -e "${GREEN}subenum finished${NC}" | notify -silent -bulk
