#!/bin/bash

# Check if the correct number of arguments are passed
if [ $# -ne 1 ]; then
    echo "Usage: $0 <targets_list>"
    exit 1
fi

targets_list="$1"

# Notify that the subdomain enumeration is starting
echo "Subdomain enumeration started" | notify

# Set up necessary directories
mkdir -p ~/nuclei-templates/http/takeovers takeover

# Download the latest subdomain takeover template for Nuclei
curl -sS -L https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/8b2bc8ab8ef801d4342bb4ec4fedb5460296da29/subdomain-takeover/detect-all-takeovers.yaml -o ~/nuclei-templates/http/takeovers/detect-all-takeovers.yaml

# Download the latest resolvers.txt file
rm -f ~/wordlist/resolvers.txt
curl -sS -L https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt -o ~/wordlist/resolvers.txt

# Perform subdomain enumeration using various tools
cat "$targets_list" | while read target; do
    sublist3r -d "$target" | anew sublist3r_"$target".txt
    findomain -t "$target" -u findomain_"$target".txt
    subfinder -all -d "$target" -o subfinder_"$target".txt
    shodanx subdomain -d "$target" -to 50 -ra -o shodan_"$target".txt
    shuffledns -mode bruteforce -w ~/wordlist/dns/best-dns-wordlist.txt -r ~/wordlist/resolvers.txt -d "$target" -o shuffledns_bruteforce_"$target".txt
done

# Concatenate all subdomain enumeration results and process with shuffledns
cat sublist3r_*.txt findomain_*.txt subfinder_*.txt shodan_*.txt shuffledns_bruteforce_*.txt | sed 's/\*\.\?//g' | sort -u | shuffledns -mode resolve -r ~/wordlist/resolvers.txt -o resolved_subdomains.txt

# Clean up temporary files
rm sublist3r_*.txt findomain_*.txt subfinder_*.txt shodan_*.txt shuffledns_bruteforce_*.txt

# Notify that nuclei takeover is starting
echo "nuclei takeover started" | notify

# Run Nuclei for subdomain takeover detection
cat resolved_subdomains.txt | httpx | nuclei -t ~/nuclei-templates/http/takeovers/ -o takeover/nuclei-takeover.txt

# Notify completion and send notifications for detected takeovers
cat takeover/nuclei-takeover.txt | notify -bulk

# Notify that the subdomain enumeration is done
echo "Subdomain enumeration done" | notify
